plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\plini\\OneDrive\\Desktop\\RSLacademy\\MazyOS\\clientes\\RSLAcademy\\site"
publishOrigin = "default"
base = "C:\\Users\\plini\\OneDrive\\Desktop\\RSLacademy\\MazyOS\\clientes\\RSLAcademy\\site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]